### ISSUE TITLE
Upload on conda/PyPI

### ISSUE THREAD

**Issue by grst** [calico/solo#17]
Hi, 

I had a look at your preprint and it really looks promising!

It would be cool if you could upload the package on bioconda and/or PyPI. 
This makes it easier to define it as a dependency in a workflow (e.g. through a conda [yml](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) file) compared to installing it from the git repository. 

Best, 
Gregor

**Comment by njbernstein** [comment]
Yes. That's a really reasonable request. I'll work on adding this to pypi this week.

**Comment by njbernstein** [comment]
@grst  it should be installable via pypi `pip install solo-sc`. Let me know if you have any issues

**Comment by grst** [comment]
Awesome!
