### ISSUE TITLE
3K PBMC & AnnData Output

### ISSUE THREAD

**Issue by hisplan** [calico/solo#21]
I have two questions:

## 1

I tried solo on 3K PBMCs from a Healthy Donor (available at 10x), and I got about 313 doublets out of 2,828 (just counted the number of `True` in `is_doublet.npy`). I thought it's a bit too much, but I'm just curious whether you have tried it before, and if so, does this number sound right to you?

## 2

I supplied `-a` to get an AnnData output, but when I tried to load the generated .h5ad file, I got this error message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-ac5b857875b6> in <module>
----> 1 adata = sc.read_h5ad(os.path.join(path_data, "out/pbmc/soloed.h5ad"))

~/miniconda/envs/notebook/lib/python3.6/site-packages/anndata/readwrite/read.py in read_h5ad(filename, backed, chunk_size)
    445     else:
    446         # load everything into memory
--> 447         constructor_args = _read_args_from_h5ad(filename=filename, chunk_size=chunk_size)
    448         X = constructor_args[0]
    449         dtype = None

~/miniconda/envs/notebook/lib/python3.6/site-packages/anndata/readwrite/read.py in _read_args_from_h5ad(adata, filename, mode, chunk_size)
    500     if not backed:
    501         f.close()
--> 502     return AnnData._args_from_dict(d)
    503 
    504 

~/miniconda/envs/notebook/lib/python3.6/site-packages/anndata/core/anndata.py in _args_from_dict(ddata)
   2155             if d_true_keys[true_key] is not None:
   2156                 for key in keys:
-> 2157                     if key in d_true_keys[true_key].dtype.names:
   2158                         d_true_keys[true_key] = pd.DataFrame.from_records(
   2159                             d_true_keys[true_key], index=key)

AttributeError: 'dict' object has no attribute 'dtype'
```

Thanks!

**Comment by njbernstein** [comment]
Hi there

Could you send me the link you used to download the pbmc data? 

Does the same error occur when you use anndata.read from the anndata package?

I'm on vacation till Tuesday so I will be slow responding sorry. 
@hisplan

**Comment by hisplan** [comment]
Okay, apparently there was a small mistake on my side while dealing with multiple datasets, so I updated the numbers, but if you could confirm the numbers, that would be great!

- `scanpy.read_h5ad` didn't work for my own dataset, but worked fine for PBMC 3K.
- `anndata.read_h5ad` worked fine for my own dataset.

Another problem with my dataset was there was a slight discrepancy between the length of `is_doublet` and the length of the resulting `adata` from solo. Have you seen this issue before?

PBMC 3K dataset can be found here: http://cf.10xgenomics.com/samples/cell-exp/1.1.0/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz which is from this webpage (https://support.10xgenomics.com/single-cell-gene-expression/datasets/1.1.0/pbmc3k).

**Comment by njbernstein** [comment]
@hisplan I havent seen that issue before.
@hisplan 

I reran solo on this dataset. When I load it up I get the following number of cells by genes:
```
pbmc = sc.read_10x_mtx("/home/nicholas/projects/genomics/scrnaseq/doublets/data/10x/pbmc/filtered_gene_bc_matrices/hg19")
AnnData object with n_obs × n_vars = 2700 × 32738 
    var: 'gene_ids'
```
I'm not sure why you have `2,828` cells and I have 2700 cells.

When I run solo I get `192` doublets, and the `is_doublets` vector if of length 2700. So I'm not seeing the same issue as you where the `is_doublets.npy` is not the right length. 
The results of Solo are always going to be stochastic but it looks like we are in the same ballpark.

Here's the UMAP with the solo scores:
<img width="698" alt="Screen Shot 2020-02-13 at 8 39 47 AM" src="https://user-images.githubusercontent.com/6864886/74456990-7cfa3c80-4e3c-11ea-822a-27c46b4d54d6.png">

Additionally, I have no issuen reading the `soloed.h5ad` file the solo can output. Here's the version of scanpy I'm using
(solo6) nicholas@sci-pvm-nicholas:~/projects/genomics/scrnaseq/doublets/analysis/github_help$ pip freeze | grep scanpy
scanpy==1.4.3
```

**Comment by hisplan** [comment]
Thanks for your quick reply. I was able to resolve the issue after upgrading both `scanpy` and `anndata` packages.

```
sc.logging.print_versions()
scanpy==1.4.5.post3 anndata==0.7.1
```

Will close this ticket.
