### ISSUE TITLE
a feedback on compatiblility with scvi_0.6.0

### ISSUE THREAD

**Issue by hy395** [calico/solo#22]
I tried to install solo with scvi_0.6.0, and it mostly is compatible except for line 124 in solo.py. scvi_0.6.0 expect toarray() (numpy.ndarray) instead of todense() (numpy.matrix). This might or might not need a fix since currently solo installation is just dependent on scvi_0.4.0.

**Comment by njbernstein** [comment]
@hy395 thanks for pointing this out. I'll release a new version soon. Until then this branch works https://github.com/calico/solo/tree/final_before_paper

**Comment by njbernstein** [comment]
Done
