### ISSUE TITLE
Have solo consume 10x directory directly

### ISSUE THREAD

**Issue by njbernstein** [calico/solo#25]
Have solo consume 10x directory directly. scVI now handles this for us so it should not be brittle. 

Rough sketch:
use scVI 10xDataset function
provide some light feedback to users about whether they should further QC the data

**Comment by njbernstein** [comment]
cc: @davek44

**Comment by davek44** [comment]
The challenge that I see is that we'd be taking on the responsibility of filtering cells and genes. I think there's a good argument to letting the analyst make those choices before letting scVI touch the data.
