### ISSUE TITLE
sklearn.metrics error

### ISSUE THREAD

**Issue by guensen0** [calico/solo#32]
Hi,

during creation of a new conda environment and install of solo by:
conda create -n solo python=3.7 && conda activate solo && pip install solo-sc
I got the following error:
ERROR: umap-learn 0.4.3 has requirement numba!=0.47,>=0.46, but you'll have numba 0.45.0 which is incompatible.
ERROR: scvi 0.6.0 has requirement llvmlite==0.30.0, but you'll have llvmlite 0.32.1 which is incompatible.

I manually install the required versions by:
conda install cython numba=0.49.1 llvmlite=0.30.0

now, install of solo-sc works without errors, but if I'm trying to run I got the error:
Traceback (most recent call last):
  File "/home/sguenth/.conda/envs/solo/bin/solo", line 5, in <module>
    from solo.solo import main
  File "/home/sguenth/.conda/envs/solo/lib/python3.7/site-packages/solo/__init__.py", line 5, in <module>
    from . import hashsolo, utils
  File "/home/sguenth/.conda/envs/solo/lib/python3.7/site-packages/solo/hashsolo.py", line 13, in <module>
    from sklearn.metrics import calinski_harabaz_score
ImportError: cannot import name 'calinski_harabaz_score' from 'sklearn.metrics' (/home/sguenth/.conda/envs/solo/lib/python3.7/site-packages/sklearn/metrics/__init__.py)

Could you please help out. Thanks in advance.

**Comment by njbernstein** [comment]
@guensen0  ahh I should have this fixed within the hour. 

Sorry about this.

**Comment by njbernstein** [comment]
@guensen0 This has been fixed in release 0.5. 

Remove your current solo and enviroment and rerun:
`conda create -n solo python=3.7 && conda activate solo && pip install solo-sc`
or run:
`conda create -n solo2 python=3.7 && conda activate solo2 && pip install solo-sc`

I'm going to close this issue. If the problem persists feel free to re-open this issue
