### ISSUE TITLE
json variables

### ISSUE THREAD

**Issue by drneavin** [calico/solo#34]
Hello,

I am interested in using solo for doublet detection and I was wondering if you could provide more details about the variables in the json file that are used for the model and how one might change the values based on their dataset?

Thanks!
-Drew

**Comment by njbernstein** [comment]
Hi there,

The variables in the JSON file should be applicable to most datasets. The only improvements I've seen for some datasets are setting `n_latent` to 64. 
```
{
    "n_hidden": 128,
    "n_latent": 16,
    "cl_hidden": 64,
    "cl_layers": 1,
    "dropout_rate": 0.1,
    "learning_rate": 0.001,
    "valid_pct": 0.10
}
```

See supp figure 12 for exploration of some of these parameters: https://www.biorxiv.org/content/10.1101/841981v1.full.pdf

If you feel Solo is not performing well for some reason let me know and I'll help troubleshoot, but it should work off the shelf based off my testing.

**Comment by njbernstein** [comment]
I'm gonna close this issue.
