### ISSUE TITLE
h5ad dataset

### ISSUE THREAD

**Issue by xinyiwangjuno** [calico/solo#40]
Hi, I would like to compare the results of different doublet detection models using the dataset 'Kang et al. Control PBMCs (2c)' mentioned in your paper. Since there's no h5ad file format of this dataset available online, would you please offer the dataset 'Kang et al. Control PBMCs (2c)' of h5ad file format?

Thank you so much

**Comment by njbernstein** [comment]
Hi @xinyiwangjuno 

[Uploading 2c.h5ad.gz…](Here's a gzipped version of the 2c h5ad file)
