### ISSUE TITLE
scipy error

### ISSUE THREAD

**Issue by dylanmr** [calico/solo#43]
Hi, 

I am attempting to implement the hash demultiplexing pipeline described in the vignette. I have generated h5ad files using the KITE pipeline from kallisto and am able to cleanly demultiplex using the seurat pipeline.

When I try to run solo I keep getting this error:

![image](https://user-images.githubusercontent.com/12213489/86335522-e4c7ed00-bc4e-11ea-8eb5-ae8fcc881b66.png)

Do you have any suggestions? 

Best,
Dylan

**Comment by njbernstein** [comment]
Hi @dylanmr yes I do. 

The master version on github has a fix for this, but I haven't made it pip installable yet. I'm guessing you installed from pip.

I'll put pushing a new release to pypi on my to-do list for today.

**Comment by njbernstein** [comment]
The fix has been released to pypi let me know if your issue is not fixed
