### ISSUE TITLE
Output Recommendation

### ISSUE THREAD

**Issue by drneavin** [calico/solo#45]
Hi solo developers,

I am interested in using solo but noticed that all the outputs are in numpy formats. I think it would be helpful to have bash-readable file outputs so that the user is not required to use python to see the results following running the software. Any chance this could be implemented for solo?

**Comment by njbernstein** [comment]
Hi @drneavin 

This could be implemented. I assume a tab-delimited format of the following files would be sufficient:
```
is_doublet.npy 

preds.npy 

softmax_scores.npy 

no_update_softmax_scores.npy

logit_scores.npy 
```
correct?

**Comment by njbernstein** [comment]
I would have each remain its own file

**Comment by drneavin** [comment]
Yes, tab delimited formats for those files would be great!

**Comment by njbernstein** [comment]
files are added as output to master. Not gonna do another `pypi` release until there are more changes
