### ISSUE TITLE
limited reproducibility

### ISSUE THREAD

**Issue by grst** [calico/solo#52]
Hi, 

I applied solo to an immune cell dataset and it appears to work quite well. 
However, I get (slightly) different results every time I run solo, which is a bit annoying as this also changes the downstream clustering step. 

Is there any way to make solo's result reproducible (such as setting a seed)? I would like to be able to share my entire analysis as a reproducible pipeline in the end. 

Best, 
Gregor

**Comment by njbernstein** [comment]
Hi @grst 

I can add the ability to set a seed. 

Best,
Nick

**Comment by grst** [comment]
Hi Nick, 

that would be awesome!

**Comment by njbernstein** [comment]
@grst Really sorry about the slow turn around on this. You should be able to install the changes doing the following:
```
git clone git@github.com:calico/solo.git && cd solo && conda create -n solo python=3.6 && conda activate solo && pip install -e .
```

**Comment by grst** [comment]
thanks a lot for implementing this! I'll give it a try after the holidays.
