### ISSUE TITLE
2c.h5ad doesn't contain gene names

### ISSUE THREAD

**Issue by brianpenghe** [calico/solo#59]
I was trying to use the h5ad data files collected by the paper. However, that 2c.h5ad doesn't contain gene names - nor does it contain cell type labels. 
Is there any chance you can provide complete h5ad data files you used for doublet detection demonstration?

Thanks!

**Comment by njbernstein** [comment]
@brianpenghe You don't need cell types or gene names to detect doublets, so I just converted the matrix file to an h5ad for my purposes. If you need that information I'd use the files from GEO. https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96583
