### ISSUE TITLE
h5ad for HashSolo &  solo .pdf plots output

### ISSUE THREAD

**Issue by DanSchnell** [calico/solo#63]
Hi,

I'd like to run HashSolo on an experiment, but am not sure about the structure/specification of the h5ad input file...

<img width="579" alt="Screen Shot 2021-05-10 at 5 46 40 PM" src="https://user-images.githubusercontent.com/38895089/117729408-c7da3f80-b1b8-11eb-98a8-d2013fa8e3f7.png">

Is there anything beyond reading it into an anndata object & writing out the h5?

Also, ran solo on the (a?) pbmc dataset but the 4 .pdf files did not appear in the solo_out directory... Should they automatically be produced?

Thanks much!

**Comment by njbernstein** [comment]
Hi there,

Nope. Nothing else extra. Although make sure your cells are your rows so youll need to transpose your table above.

For more info about anndata see here: http://falexwolf.de/blog/171223_AnnData_indexing_views_HDF5-backing/

I'll investigate the plotting issue

**Comment by DanSchnell** [comment]
Thanks very much for this guidance & looking into the plotting.

From: njbernstein ***@***.***>
Reply-To: calico/solo ***@***.***>
Date: Wednesday, May 12, 2021 at 12:34 PM
To: calico/solo ***@***.***>
Cc: "Schnell, Daniel (Dan)" ***@***.***>, Author ***@***.***>
Subject: Re: [calico/solo] h5ad for HashSolo & solo .pdf plots output (#63)


***This email originated from an EXTERNAL sender to CCHMC. Proceed with caution when replying, opening attachments, or clicking links in this message.***



Hi there,

Nope. Nothing else extra. Although make sure your cells are your rows so youll need to transpose your table above.

For more info about anndata see here: http://falexwolf.de/blog/171223_AnnData_indexing_views_HDF5-backing/

I'll investigate the plotting issue
