### ISSUE TITLE
Solo in line?

### ISSUE THREAD

**Issue by cnk113** [calico/solo#76]
Hello,

I was wondering if it possible to run solo in line? I noticed hashsolo has the capabilities, but would like to run solo in line as well.

Thanks,
Chang

**Comment by davek44** [comment]
Hi Chang, could you be more specific about what you mean by "in line"?

**Comment by davek44** [comment]
We didn't implement anything like that, but scvi-tools absorbed Solo and you might be able to do it that way https://docs.scvi-tools.org/en/stable/user_guide/models/solo.html. I haven't tried it though.
