### ISSUE TITLE
Dependencies are too strict

### ISSUE THREAD

**Issue by JoshLoecker** [calico/solo#86]
Would it be possible to use `>=` instead of `==` in the package dependencies? As it stands, each time a package is updated, these dependencies will have to be updated manually and will inevitably cause a conflict, which is what I am trying to solve now.

Pull request #82 modified the dependencies to be quite strict, and most packages listed below are out of date just a few months after these changes. An example `requirements.txt` could be something like:

```diff
- ConfigArgParse==1.7
+ ConfigArgParse>=1.7,<2.0
- h5py==3.10.0
+ h5py>=3.10.0,<4.0
- leidenalg==0.10.2
+ leidenalg>0.10.2,<1.0
- lightning>=2
+ lightning>=2,<3.0
- lightning-utilities==0.10.1
+ lightning-utilities>=0.10.1,<1.0
- numba==0.59.0
+ numba>=0.59.0,<1.0
- pandas==2.2.1
+ pandas>=2.0
- pytorch-lightning==2.2.1
+ pytorch-lightning>=2.2.1,<3.0
- scanpy==1.9.8
+ scanpy>=1.9.8,<2.0
- scipy==1.12.0
+ scipy>=1.12.0,<2.0
- scvi-tools==1.1.2
+ scvi-tools>=1.1.1,<2.0
- seaborn==0.13.2
+ seaborn>=0.13.2,<1.0
- torch==2.2.1
+ torch>=2.2.1,<3.0
- torchmetrics==1.3.1
+ torchmetrics>=1.3.1,<2.0
- tqdm==4.66.2
+ tqdm>=4.66.2,<5.0
```

If this is something you're open to, I can make a pull request. Thanks for any help :)

**Comment by davek44** [comment]
Fine with me. Go for it! Thanks
