### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mzhibo** [calico/solo#9]
Hi,
When I tried to install the package, it gave some error. Any idea what could be causing this and how to fix it?
I am installing as you instructed in a new conda enviroment with python 3.6.9.
log:
... (omitted the non-error lines)
Collecting ptyprocess>=0.5
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
**ERROR: jupyter-console 6.0.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 3.0.2 which is incompatible.**
Installing collected packages: ConfigArgParse, six, cycler, decorator, numpy, h5py, joblib, mock, natsort, networkx, numexpr, python-dateutil, pytz, pandas, patsy, Pillow, pyparsing, scipy, anndata, llvmlite, numba, scikit-learn, umap-learn, tqdm, kiwisolver, matplotlib, statsmodels, seaborn, tables, scanpy, cloudpickle, future, hyperopt, click, numpy-groupies, loompy, torch, xlrd, ipython-genutils, traitlets, pygments, jupyter-core, tornado, pyzmq, jupyter-client, parso, jedi, pickleshare, ptyprocess, pexpect, wcwidth, prompt-toolkit, backcall, ipython, ipykernel, qtconsole, jupyter-console, pyrsistent, attrs, more-itertools, zipp, importlib-metadata, jsonschema, nbformat, Send2Trash, terminado, prometheus-client, webencodings, bleach, testpath, mistune, entrypoints, pandocfilters, defusedxml, MarkupSafe, jinja2, nbconvert, notebook, widgetsnbextension, ipywidgets, jupyter, scvi, dataclasses, python-igraph, leidenalg, atomicwrites, packaging, py, pluggy, pytest, solo

  Running setup.py develop for solo
  **ERROR: Command errored out with exit status -11:
     command: /home/mzhibo/anaconda3/envs/solo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mzhibo/apps/solo/setup.py'"'"'; __file__='"'"'/home/mzhibo/apps/solo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/mzhibo/apps/solo/
    Complete output (1 lines):
    [2019-12-17 13:53:26,158] INFO - scvi._settings | Added StreamHandler with custom formatter to 'scvi' logger.**
    ----------------------------------------

**ERROR: Command errored out with exit status -11: /home/mzhibo/anaconda3/envs/solo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mzhibo/apps/solo/setup.py'"'"'; __file__='"'"'/home/mzhibo/apps/solo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.**

**Comment by njbernstein** [comment]
Hi @mzhibo  

Thanks for trying Solo out! I really appreciate it. I've fixed the install issue I believe. Please let me know if the issue is not fixed. 
commit to the fix https://github.com/calico/solo/commit/cc206ce5ffe2c4b8403243190ae39baa0a06e6ff

If you have any other issues let me know.

**Comment by massonix** [comment]
Hi @njbernstein,

Thanks for developing this useful package. I ran into a similar error when installing solo in our cluster (no problems in my own machine):

```

ERROR: Command errored out with exit status 1:
     command: /apps/PYTHON/3.8.6/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch_tmp/pip-install-zy1244ss/solo-sc/setup.py'"'"'; __file__='"'"'/scratch_tmp/pip-install-zy1244ss/solo-sc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /scratch_tmp/pip-record-7hzjy9tz/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/devel/rmassoni/.local/include/python3.8/solo-sc
         cwd: /scratch_tmp/pip-install-zy1244ss/solo-sc/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/scratch_tmp/pip-install-zy1244ss/solo-sc/setup.py", line 9, in <module>
        from solo import __author__, __email__
      File "/scratch_tmp/pip-install-zy1244ss/solo-sc/solo/__init__.py", line 5, in <module>
        from . import hashsolo, utils
      File "/scratch_tmp/pip-install-zy1244ss/solo-sc/solo/utils.py", line 3, in <module>
        from scvi.dataset import GeneExpressionDataset
      File "/home/devel/rmassoni/.local/lib/python3.8/site-packages/scvi/__init__.py", line 14, in <module>
        from ._settings import set_verbosity, set_seed
      File "/home/devel/rmassoni/.local/lib/python3.8/site-packages/scvi/_settings.py", line 5, in <module>
        import torch
      File "/home/devel/rmassoni/.local/lib/python3.8/site-packages/torch/__init__.py", line 189, in <module>
        _load_global_deps()
      File "/home/devel/rmassoni/.local/lib/python3.8/site-packages/torch/__init__.py", line 142, in _load_global_deps
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
      File "/apps/PYTHON/3.8.6/lib/python3.8/ctypes/__init__.py", line 373, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/devel/rmassoni/.local/lib/python3.8/site-packages/torch/lib/libgomp-7c85b1e2.so.1)
    ----------------------------------------
ERROR: Command errored out with exit status 1: /apps/PYTHON/3.8.6/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/scratch_tmp/pip-install-zy1244ss/solo-sc/setup.py'"'"'; __file__='"'"'/scratch_tmp/pip-install-zy1244ss/solo-sc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /scratch_tmp/pip-record-7hzjy9tz/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/devel/rmassoni/.local/include/python3.8/solo-sc Check the logs for full command output.
```
Should I install it from the commit above?

Thanks,

R

**Comment by njbernstein** [comment]
It seems like your PyTorch installation is not correct. You need to install `GLIBC_2.14`. 

Here's a link to solving what seems to be a common problem:
https://gist.github.com/michaelchughes/85287f1c6f6440c060c3d86b4e7d764b

**Comment by njbernstein** [comment]
@massonix  ^^

**Comment by massonix** [comment]
Thanks a lot, Nick! I will check with our cluster administrator.
